site:
  title: Magnolia Cloud Service Internal Documentation
  # # the 404 page and sitemap files only get generated when the url property is set
  url: http://docs.beta.de.magnolia-cloud.com/
  start_page: magnolia-saas:ROOT:index.adoc
  robots: allow

content:
  sources:
  - url: https://git.magnolia-cms.com/scm/cloud/magnolia-cloud.git
    branches: [master]
    start_path: docs
  - url: https://git.magnolia-cms.com/scm/DOCUMENTATION/product-docs.git
    branches: [master]

urls:
  # html_extension_style: drop
  redirect_facility: static

ui:
  bundle:
    url: ./ui/build/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"

# output:
#   dir: ./public

# Global asciidoc attributes here
asciidoc:
  attributes:
    ui: Cockpit
    fields-dir: /Templating/Dialog-definition/Field-definition/List-of-fields/
    solution-type: SaaS
    hosting-country: Switzerland
    magnolia-latest-version: 6.2.9
    kroki-fetch-diagram: true
  extensions:
  - ./lib/tabs-block.js
  - asciidoctor-kroki
