site:
  title: Magnolia Cloud Service Internal Documentation
  # # the 404 page and sitemap files only get generated when the url property is set
  url: https://saas-docs.beta.de.magnolia-cloud.com/saas/
  start_page: saas:ROOT:index.adoc
  robots: allow

content:
  sources:
  - url: https://git.magnolia-cms.com/scm/cloud/magnolia-cloud.git
    start_path: docs
    branches: [master]
  - url: https://git.magnolia-cms.com/scm/DOCUMENTATION/product-docs.git
    branches: [master]
  - url: https://git.magnolia-cms.com/scm/cloud/mgnlctl.git
    start_path: docs
    branches: [master]
  - url: https://gitlab.com/magnolia-major-tom/major-tom-documentation.git
    start_path: docs
    branches: [master]
  - url: https://git.magnolia-cms.com/scm/incubator/workflow-extended.git
    start_path: docs
    branches: [master]
  - url: https://git.magnolia-cms.com/scm/services/url-translation.git
    start_path: docs
    branches: [master]
  - url: https://git.magnolia-cms.com/scm/incubator/incubator-module-docs.git
    branches: [master]

urls:
  html_extension_style: indexify

ui:
  bundle:
    url: ./ui/build/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"

# output:
#   dir: ./public

# Global asciidoc attributes here
asciidoc:
  attributes:
    page-pagination: true
    check-mark: '&#x2714;'
    ui: Cockpit
    fields-dir: /Templating/Dialog-definition/Field-definition/List-of-fields/
    solution-type: SaaS
    hosting-country: Switzerland
    magnolia-latest-version: 6.2.9
    kroki-fetch-diagram: true
    figure-caption!:
    jira: https://jira.magnolia-cms.com/browse/
    mla: link:https://www.magnolia-cms.com/mla.html[MLA^]
    gpl: link:http://www.gnu.org/licenses/gpl-3.0.html[GPL^]
  extensions:
  - ./lib/tabs-block.js
  - asciidoctor-kroki
